### ISSUE TITLE
Can't install with NPM

### ISSUE THREAD

**Issue by mbabker** [elkuku/g11n-js#1]
I'm trying a new build setup that uses NPM to phase out the deprecated Bower and this repo isn't installable with NPM in any way (even using `"g11n-js": "github:elkuku/g11n-js"` to declare the dependency in `package.json`).

**Comment by elkuku** [comment]
Well - I added a `package.json` file, so at least it should be npm installable now...

I also "published" my "package" so could you check again using `g11n-js` please?

**Comment by mbabker** [comment]
All good, thanks!
